default: &default
  docker:
  - image: choerodon/cibase:latest

version: 2
jobs:
  docker_build:
    <<: *default
    steps:
      - setup_remote_docker:
          version: 17.05.0-ce
      - checkout
      - attach_workspace:
          at: .
      - run: |
          sed -i "s;dockerhub.azk8s.cn/library/; ;g" Dockerfile
          docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
          docker build -t ${DOCKER_GROUP_NAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG} .
          docker push ${DOCKER_GROUP_NAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}

  helm_chart_build:
    <<: *default
    steps:
      - checkout
      - run: |
          CHART_PATH=`find . -name Chart.yaml`
          yq w -i ${CHART_PATH%/*}/values.yaml image.repository ${DOCKER_GROUP_NAME}/${PROJECT_NAME}
          yq w -i ${CHART_PATH%/*}/values.yaml image.tag ${CIRCLE_TAG}
          helm repo add choerodon "${CHART_REPOSITORY}/${CHART_ORGANIZATION}/${CHART_PROJECT}/"
          helm push --username ${HELM_USER} --password ${HELM_PASSWORD} ${CHART_PATH%/*} --version ${CIRCLE_TAG} choerodon

workflows:
  version: 2
  release:
    jobs:
      - docker_build:
        context: org-global
        filters:
          tags:
            only: /^.*/
          branches:
            only:
              - /^release-.*$/
      - helm_chart_build:
        context: org-global
        requires:
          - docker_build
        filters:
          tags:
            only: /^.*/
          branches:
            only:
              - /^release-.*$/